project:
  type: website
  output-dir: _site
  preview:
    port: 4200

website:
  site-url: arachnidly.github.io/learning/
  title: Learning :)
  sidebar:
    collapse-level: 2
    collapsible: true
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Random Math"
        contents:
          - href: pages/random/Fourier.qmd
            text: Fourier Series Representations
          - href: pages/random/Vectors-in-alternate-basis.qmd
            text: Vectors in Alternate Basis
      - section: "Reinforcement Learning"
        contents:
          - href: pages/RL/Multi-armed-bandits.qmd
            text: Multi-armed Bandits
      - section: "Statistics"
        contents:
          - href: pages/Stats/Probability-Basics.qmd
            text: Basic Concepts of Probability
      - href: originals/index.qmd
        text: Original Works
  open-graph: true
            
format:
  html:
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly
    toc: true

html-math-method: mathjax

execute: 
  freeze: auto